# MineCollector v1.1.0 Schema
enabled: {type: bool, required: true}

# ========= SCORING =========
scoring:
  collection enabled: {type: bool, required: true}
  collection score: {type: float, required: true}

  stack enabled: {type: bool, required: true}
  stack multiple: {type: int, required: true, min: 2}
  stack score: {type: float, required: true}

  advancement enabled: {type: bool, required: true}
  advancement scores:
    task: {type: float, required: true}
    goal: {type: float, required: true}
    challenge: {type: float, required: true}

# ========= ANNOUNCEMENT =========
announcement:
  collection: {type: str, required: true, pattern: '^(all players|self|none)$'}
  high level reached: {type: str, required: true, pattern: '^(all players|self|none)$'}
  high level minimum: {type: int, required: true, min: 2}
  advancement: {type: str, required: true, pattern: '^(all players|self|none)$'}

# ========= GAME =========
game:
  hide unknown collection: {type: bool, required: true}
  respawn enderegg: {type: bool, required: true}

# ========= DB =========
db:
  autosave period: {type: int, required: true, min: 1}
  autosave logging: {type: bool, required: true}